### ISSUE TITLE
有计划更新1.19.2版本嘛？

### ISSUE THREAD

**Issue by MICOAST** [OptiJava/OptCarpetAddition#5]
不强求，但是真的很需要假人生成优化与tp

**Comment by OptiJava** [comment]
你可以先试试把1.19.3版本的jar文件用压缩文件打开，找到`fabric.mod.json`文件，把里面的“minecraft”那一项从1.19.3改为1.19.2试一下（一定别直接在生产环境试），如果不行或者功能有问题我再找时间升级（
这样改就可以：
![image](https://github.com/OptiJava/OptCarpetAddition/assets/106148777/e4fbbed2-ab0d-48da-8243-15f4620940cf)
（最近期末考试没时间

**Comment by MICOAST** [comment]
非常感谢
