### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by jitui-star** [OptiJava/OptCarpetAddition#7]
新出的版本为1.20.1，之后会适配1.20么

**Comment by OptiJava** [comment]
1.20.1版本直接装在1.20上应该是没问题的，你可以试一下

**Comment by jitui-star** [comment]
服务器报错了1.20的服务器不行






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月11日(星期二) 晚上8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OptiJava/OptCarpetAddition] 1.20 (Issue #7)





 
1.20.1版本直接装在1.20上应该是没问题的，你可以试一下

**Comment by OptiJava** [comment]
> 服务器报错了1.20的服务器不行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月11日(星期二) 晚上8:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [OptiJava/OptCarpetAddition] 1.20 (Issue #7) 1.20.1版本直接装在1.20上应该是没问题的，你可以试一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

发一下完整的日志、崩溃报告和模组列表

**Comment by jitui-star** [comment]
[2023-07-11-5.log.gz](https://github.com/OptiJava/OptCarpetAddition/files/12016820/2023-07-11-5.log.gz)

**Comment by jitui-star** [comment]
报错内容我看到就一个opt有问题

**Comment by OptiJava** [comment]
找到opt-carpet-addition的模组jar文件，使用压缩文件打开，找到`fabric.mod.json`文件，将“~1.20.1”替换成"1.20.x"应该可以解决问题
![image](https://github.com/OptiJava/OptCarpetAddition/assets/106148777/2a0cda8d-c02a-48d1-a590-2e96a46d31f0)

**Comment by jitui-star** [comment]
还是不行，我试过了 
[2023-07-12-4.log.gz](https://github.com/OptiJava/OptCarpetAddition/files/12023015/2023-07-12-4.log.gz)
这是日志 然后已经改成1.20.x了

**Comment by jitui-star** [comment]
ok 已经跑起来了 “~1.20.1”我第一次改成“~1.20.x”，~没删导致出报错 谢谢作者
