### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by SirPotato42** [OptiJava/OptCarpetAddition#9]
Could the mod be updated to 1.20.4 for fabric?
Changing fabric.mod.json to 1.20.4 does not work.

**Comment by OptiJava** [comment]
I'm sorry but I'm in grade 9 now. It may take a long time to complete the upgrade.
Thank you for your support and understanding. :)

**Comment by OptiJava** [comment]
ok, completed. 
Hopefully it works.
